# Generated by Django 5.1.6 on 2025-02-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_studyevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studyevent',
            old_name='coordinate_lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='studyevent',
            old_name='coordinate_lon',
            new_name='longitude',
        ),
        migrations.RemoveField(
            model_name='studyevent',
            name='attendees',
        ),
        migrations.RemoveField(
            model_name='studyevent',
            name='host',
        ),
        migrations.RemoveField(
            model_name='studyevent',
            name='invited_friends',
        ),
        migrations.AddField(
            model_name='studyevent',
            name='invited_friends',
            field=models.TextField(blank=True),
        ),
    ]
