# Generated by Django 5.1.6 on 2025-02-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_userprofile_is_certified'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyevent',
            name='event_type',
            field=models.CharField(choices=[('study', 'Study'), ('party', 'Party'), ('business', 'Business'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
