name: Deploy to DigitalOcean App Platform

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to DigitalOcean App Platform
      uses: digitalocean/app_action@v1
      with:
        app_id: ${{ secrets.DIGITALOCEAN_APP_ID }}
        api_token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
