# Generated by Django 5.1.6 on 2025-02-18 14:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_coordinate_lat_studyevent_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyevent',
            name='invited_friends',
        ),
        migrations.AddField(
            model_name='studyevent',
            name='invited_friends',
            field=models.ManyToManyField(blank=True, related_name='invited_study_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
