# Generated by Django 5.1.6 on 2025-02-18 16:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_studyevent_host'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studyevent',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='attending_study_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
