# Generated by Django 5.1.6 on 2025-02-19 12:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_studyevent_attendees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyevent',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
