# Generated by Django 5.1.6 on 2025-02-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_studyevent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
