# Generated by Django 5.1.6 on 2025-02-20 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_studyevent_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyevent',
            name='end_time',
        ),
    ]
