# Generated by Django 5.1.6 on 2025-02-20 10:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_studyevent_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyevent',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
