# Generated by Django 5.1.6 on 2025-02-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_studyevent_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_certified',
            field=models.BooleanField(default=False, help_text='True if this user is allowed to create public events.'),
        ),
    ]
