# Generated by Django 5.1.6 on 2025-03-06 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_eventcomment_eventshare_eventlike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventlike',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='eventlike',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='myapp.eventcomment'),
        ),
        migrations.AlterField(
            model_name='eventshare',
            name='shared_platform',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('other', 'Other Platform')], default='other', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='eventlike',
            unique_together={('event', 'user', 'comment')},
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.eventcomment')),
            ],
        ),
    ]
