# Generated by Django 5.1.6 on 2025-03-09 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_eventlike_unique_together_eventlike_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclinedInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declined_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declined_by', to='myapp.studyevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declined_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Declined Invitation',
                'verbose_name_plural': 'Declined Invitations',
                'unique_together': {('user', 'event')},
            },
        ),
    ]
