# Generated by Django 5.1.6 on 2025-03-20 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_declinedinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyevent',
            name='auto_matching_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studyevent',
            name='interest_tags',
            field=models.JSONField(blank=True, default=list, help_text='JSON array of interest tags for matching'),
        ),
        migrations.AddField(
            model_name='studyevent',
            name='max_participants',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='auto_invite_enabled',
            field=models.BooleanField(default=True, help_text='Whether user wants to receive automatic invites'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interests',
            field=models.JSONField(blank=True, default=list, help_text='JSON array of user interests'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_radius',
            field=models.FloatField(default=10.0, help_text='Preferred radius in km for event matching'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.JSONField(blank=True, default=dict, help_text='JSON object mapping skill names to skill levels'),
        ),
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=100)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_items', to='myapp.userprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'interest')},
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('EXPERT', 'Expert')], default='BEGINNER', max_length=20)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_items', to='myapp.userprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'skill')},
            },
        ),
    ]
