# Generated by Django 5.1.6 on 2025-03-20 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_studyevent_auto_matching_enabled_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userskill',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userskill',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='studyevent',
            name='auto_matching_enabled',
        ),
        migrations.RemoveField(
            model_name='studyevent',
            name='interest_tags',
        ),
        migrations.RemoveField(
            model_name='studyevent',
            name='max_participants',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='auto_invite_enabled',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_radius',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='skills',
        ),
        migrations.DeleteModel(
            name='UserInterest',
        ),
        migrations.DeleteModel(
            name='UserSkill',
        ),
    ]
