# Generated by Django 5.2 on 2025-04-19 20:54

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_device'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyevent',
            name='auto_matching_enabled',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='studyevent',
            name='end_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='studyevent',
            name='event_type',
            field=models.CharField(choices=[('study', 'Study'), ('party', 'Party'), ('business', 'Business'), ('other', 'Other')], db_index=True, default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='studyevent',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='studyevent',
            name='time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='studyevent',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='studyevent',
            index=models.Index(fields=['is_public', 'end_time'], name='myapp_study_is_publ_b64be2_idx'),
        ),
        migrations.AddIndex(
            model_name='studyevent',
            index=models.Index(fields=['host', 'is_public'], name='myapp_study_host_id_935e28_idx'),
        ),
        migrations.AddIndex(
            model_name='studyevent',
            index=models.Index(fields=['auto_matching_enabled', 'is_public'], name='myapp_study_auto_ma_11831f_idx'),
        ),
        migrations.AddIndex(
            model_name='studyevent',
            index=models.Index(fields=['event_type', 'is_public'], name='myapp_study_event_t_bb4595_idx'),
        ),
    ]
