version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: pinit_production
      POSTGRES_USER: pinit_user
      POSTGRES_PASSWORD: pinit_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=False
      - DB_HOST=db
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=your-secret-key-change-this
      - DJANGO_SETTINGS_MODULE=StudyCon.settings_production

volumes:
  postgres_data:
